# -*- coding: utf-8 -*-

TRANSLATION_GLOSSARY = [
    ('原神', 'Genshin'),
    ('可莉', 'Klee'),
    ('迪卢克', 'Diluc'),
    ('安柏', 'Amber'),
    ('班尼特', 'Bennett'),
    ('香菱', 'Xiangling'),
    ('莫娜', 'Mona'),
    ('芭芭拉', 'Barbara'),
    ('行秋', 'Xingqiu'),
    ('琴', 'Jean'),
    ('温迪', 'Venti'),
    ('魈', 'Xiao'),
    ('旅行者', 'Traveler'),
    ('砂糖', 'Sucrose'),
    ('刻晴', 'Keqing'),
    ('北斗', 'Beidou'),
    ('丽莎', 'Lisa'),
    ('雷泽', 'Razor'),
    ('菲谢尔', 'Fischl'),
    ('七七', 'Qiqi'),
    ('凯亚', 'Kaeya'),
    ('冲云', 'Chongyun'),
    ('诺艾尔', 'Noelle'),
    ('凝光', 'Ningguang'),
    ('神里绫华', 'Kamisato Ayaka'),
    ('绫华', 'Ayaka'),
]
